#!/bin/bash
echo -e "\n"
echo "Description: This program performs a random split into training and test data, which are then stored in separate files."
echo "Further, this program calculates the k nearest neighbours of the test samples inside the training dataset and predicts the labels of the test data via majority vote."


####################################################################################
# set default variables or overwrite them by setting flags.
# -t value sets the chosen testset size (value as a fraction between 0 and 1) 
# -v switches on the verbose mode for the mlpack commands. This prints more details to the terminal.

# default values
DATASET="iris"
TESTSIZE=0.2
K=5
VERBOSE="" 

# read optional flags to set parameters
while getopts 'd:t:k:v' OPTION;
do
    case "${OPTION}" in
		d) DATASET=${OPTARG};;
        t) TESTSIZE=${OPTARG};;
        k) K=${OPTARG};;
        v) VERBOSE="-v";;
    esac
done

echo "Dataset: $DATASET, Testsetsize: $TESTSIZE"

####################################################################################
# # split the data into training and test sets and store the files into a folder called "prepared_datasets"
FEATURES_FILE=../prepared_datasets/$DATASET.data.csv
LABELS_FILE=../prepared_datasets/$DATASET.labels.csv

# create directory if it doesn't exist
mkdir -p preprocessed_data
mkdir -p predicted_data
mkdir -p neighbours_data

mlpack_preprocess_split \
	-i $FEATURES_FILE \
	-I $LABELS_FILE \
	-t preprocessed_data/$DATASET.data.train.csv \
	-l preprocessed_data/$DATASET.labels.train.csv \
	-T preprocessed_data/$DATASET.data.test.csv \
	-L preprocessed_data/$DATASET.labels.test.csv \
	-r $TESTSIZE \
	$VERBOSE

####################################################################################
# fit the knn model and predict the test dataset. Stores the predicted values into a folder called "predicted_data"

TRAINFEATURES_FILE=preprocessed_data/$DATASET.data.train.csv
TRAINLABELS_FILE=preprocessed_data/$DATASET.labels.train.csv

TESTFEATURES_FILE=preprocessed_data/$DATASET.data.test.csv
TESTLABELS_FILE=preprocessed_data/$DATASET.labels.test.csv

TESTLABELS_PREDIC_FILE="predicted_data/$DATASET.labels.test.predicted.csv"

DISTANCES_FILE=neighbours_data/$DATASET.distances.test.csv
NEIGHBOURS_FILE=neighbours_data/$DATASET.neighbours.test.csv

mlpack_knn \
	--k $K \
	--reference_file $TRAINFEATURES_FILE \
	--query_file $TESTFEATURES_FILE \
	--distances_file $DISTANCES_FILE \
	--neighbors_file $NEIGHBOURS_FILE \
	--leaf_size 30 \
 	$VERBOSE

####################################################################################
# executes the accuracy calculation (Mean Squared Error) which has been implemented in C++
cd predict_classes
./main $DATASET
cd ..

