#!/bin/bash

echo "This program performs a split into training and test data, which are then stored in separate files. \n"
echo "Further, this program fits a linear regression model with the training data and predicts the labels of the test data."

FEATURES_FILE=../../prepared_datasets/diabetes.data.csv
LABELS_FILE=../../prepared_datasets/diabetes.labels.csv

# create directory if it doesn't exist
mkdir -p preprocessed_data
mkdir -p predicted_data

# split the data into training and test sets
mlpack_preprocess_split \
	-i $FEATURES_FILE \
	-I $LABELS_FILE \
	-t preprocessed_data/diabetes.data.train.csv \
	-l preprocessed_data/diabetes.labels.train.csv \
	-T preprocessed_data/diabetes.data.test.csv \
	-L preprocessed_data/diabetes.labels.test.csv \
	-r 0.2 \
	-v

TRAINFEATURES_FILE=preprocessed_data/diabetes.data.train.csv
TRAINLABELS_FILE=preprocessed_data/diabetes.labels.train.csv

TESTFEATURES_FILE=preprocessed_data/diabetes.data.test.csv
TESTLABELS_FILE=preprocessed_data/diabetes.labels.test.csv

TESTLABELS_PREDIC_FILE=predicted_data/diabetes.labels.test.predicted.csv

# fit the linear regression model and predict the test dataset. Stores the predicted values into a folder called "predicted_data"
mlpack_linear_regression \
	--training_file  $TRAINFEATURES_FILE\
	--training_responses_file $TRAINLABELS_FILE \
	--test_file $TESTFEATURES_FILE \
	--output_predictions_file $TESTLABELS_PREDIC_FILE \
	--verbose

# executes the accuracy calculation (Mean Squared Error) which has been implemented in C++
./accuracy_calculation/main
