#!/bin/bash

echo "This program fits a linear regression model with the training data and predicts the labels of the test data."

TRAINFEATURES_FILE=preprocessed_data/diabetes.data.train.csv
TRAINLABELS_FILE=preprocessed_data/diabetes.labels.train.csv

TESTFEATURES_FILE=preprocessed_data/diabetes.data.test.csv
TESTLABELS_FILE=preprocessed_data/diabetes.labels.test.csv



mlpack_linear_regression \
	--training_file  $TRAINFEATURES_FILE\
	--training_responses_file $TRAINLABELS_FILE \
	--test_file $TESTFEATURES_FILE \
	--output_predictions_file diabetes.labels.test.predicted.csv \
	--verbose

